networks:
  bot-network: # tên của network đc tạo 
    driver: bridge

services:
  node-bot:
    container_name: node-bot
    build:
      dockerfile: Dockerfile
      context: . #address of Dockerfile
    networks:
      - bot-network
    env_file:
      - ./env/.env
    depends_on:
      - db
      - rabbitmq
      - redis
    working_dir: /usr/src/chatbotZi
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
  db:
    image: mysql:latest
    container_name: mysql-bot
    #add that(command) if client not support "caching_sha2_password"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    env_file:
      - ./env/mysql.env
    networks:
      - bot-network
    volumes:
      - ~/chatZi:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-bot
    restart: always
    ports:
      - "15673:15672"
    volumes:
      - ~/rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./env/rabbitmq.env
    networks:
      - bot-network
  nginx:
    image: nginx:alpine
    hostname: chatZi-ngnix
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/Cloudflare.cert:/etc/nginx/certs/xuongsx.site.crt
      - ./certs/Cloudflare.key:/etc/nginx/certs/xuongsx.site.key
    depends_on:
      - node-bot
    networks:
      - bot-network
  redis:
    image: redis:7.0.10
    container_name: redis-bot
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ~/redis_data_test:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bot-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    




