networks:
  bot-network: # tên của network đc tạo 
    driver: bridge

services:
  node-bot:
    container_name: node-bot
    build:
      dockerfile: Dockerfile
      context: . #address of Dockerfile
    ports:
      - "8082:8080"
    networks:
      -  bot-network
    env_file:
      - .env
    working_dir: /usr/src/chatbotZi
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
  db:
    image: mysql:latest
    container_name: mysql-bot
    #add that(command) if client not support "caching_sha2_password"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    env_file:
      - mysql.env
    ports: 
      - 3306:3306
    networks:
      - bot-network
    volumes:
      - ~/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        

