networks:
  bot-network: # tên của network đc tạo 
    driver: bridge

services:
  node-bot:
    container_name: node-bot
    build:
      dockerfile: Dockerfile
      context: . #address of Dockerfile
    ports:
      - "8083:8080"
    networks:
      -  bot-network
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /usr/src/chatbotZi
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
  db:
    image: mysql:latest
    container_name: mysql-bot
    #add that(command) if client not support "caching_sha2_password"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    env_file:
      - mysql.env
    ports: 
      - 3307:3306
    networks:
      - bot-network
    volumes:
      - ~/chatZi:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:alpine
    hostname: chatZi-ngnix
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/Cloudflare.cert:/etc/nginx/certs/xuongsx.site.crt
      - ./certs/Cloudflare.key:/etc/nginx/certs/xuongsx.site.key
    depends_on:
      - node-bot
    networks:
      - bot-network
        


